server:
  port: 8087

spring:
  application:
    name: notification-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          auth: true
          starttls:
            enable: true

aws:
  region: ${AWS_REGION:eu-north-1}


twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  phone-number: ${TWILIO_PHONE_NUMBER:}

notification:
  scheduler:
    enabled: true
    fixed-delay-ms: 60000
    batch-size: 50
  recurring:
    timezone: Asia/Kolkata
    morning-time: "09:00"
    evening-time: "18:00"
  retry:
    max-retries: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      user-service:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
    instances:
      user-service:
        baseConfig: default


