package org.notification.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.notification.model.enums.NotificationChannel;
import org.notification.model.enums.NotificationStatus;
import org.notification.model.enums.NotificationType;
import org.notification.model.enums.NotificationPriority;
import org.notification.model.enums.SendMode;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = Notification.TABLE_NAME)
public class Notification {

    public static final String TABLE_NAME = "notifications_v3";
    public static final String STATUS_SCHEDULED_INDEX = "status-scheduledAt-index";
    public static final String RECURRENCE_KEY_INDEX = "recurrence-key-index";
    public static final String BATCH_INDEX = "batch-index";
    public static final String USER_INDEX = "user-index";

    @DynamoDBHashKey(attributeName = "notificationId")
    @DynamoDBAutoGeneratedKey
    private String notificationId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = BATCH_INDEX, attributeName = "batchId")
    private String batchId;

    @DynamoDBAttribute(attributeName = "referenceId")
    private String referenceId;

    @DynamoDBAttribute(attributeName = "idempotencyKey")
    private String idempotencyKey;

    @DynamoDBVersionAttribute(attributeName = "version")
    private Long version;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = USER_INDEX, attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "recipientEmail")
    private String recipientEmail;

    @DynamoDBAttribute(attributeName = "recipientPhone")
    private String recipientPhone;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "message")
    private String message;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "type")
    private NotificationType type;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "channel")
    private NotificationChannel channel;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "priority")
    private NotificationPriority priority;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = STATUS_SCHEDULED_INDEX, attributeName = "status")
    @DynamoDBTypeConvertedEnum
    private NotificationStatus status;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "sendMode")
    private SendMode sendMode;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = STATUS_SCHEDULED_INDEX, attributeName = "scheduledAt")
    private Long scheduledAt;

    @DynamoDBAttribute(attributeName = "sentAt")
    private Long sentAt;

    @DynamoDBAttribute(attributeName = "failedAt")
    private Long failedAt;

    @DynamoDBAttribute(attributeName = "failureReason")
    private String failureReason;

    @DynamoDBAttribute(attributeName = "retryCount")
    private Integer retryCount = 0;

    @DynamoDBAttribute(attributeName = "maxRetries")
    private Integer maxRetries = 3;

    @DynamoDBAttribute(attributeName = "nextRetryAt")
    private Long nextRetryAt;

    @DynamoDBAttribute(attributeName = "recurrenceDate")
    private String recurrenceDate;

    @DynamoDBAttribute(attributeName = "recurrenceSlot")
    private String recurrenceSlot;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = RECURRENCE_KEY_INDEX, attributeName = "recurrenceKey")
    private String recurrenceKey;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = USER_INDEX, attributeName = "createdAt")
    private Long createdAt;

    @DynamoDBAttribute(attributeName = "updatedAt")
    private Long updatedAt;

    @DynamoDBAttribute(attributeName = "isRead")
    private Boolean read = false;

    @DynamoDBAttribute(attributeName = "redirectUrl")
    private String redirectUrl;

    @DynamoDBAttribute(attributeName = "expirationTime")
    private Long expirationTime;
}